services:
  coindeskapi:
    image: k3vinzz/coindeskapi:latest
    build:
      context: .
      dockerfile: src/CoindeskApi/dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80  # Set the app to listen on port 80
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=CoinDeskDb;User Id=sa;Password=123;TrustServerCertificate=True;
