services:
  coindeskapi:
    image: k3vinzz/search-svc:latest
    build:
      context: .
      dockerfile: src/CoindeskApi/dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=CoinDeskDb;Trusted_Connection=False;TrustServerCertificate=True
