# 使用 .NET 8 SDK 映像
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 as build
WORKDIR /app
EXPOSE 80

COPY Coindesk.sln Coindesk.sln
COPY src/CoindeskApi/CoindeskApi.csproj src/CoindeskApi/CoindeskApi.csproj
COPY tests/CoindeskApi.UnitTests/CoindeskApi.UnitTests.csproj tests/CoindeskApi.UnitTests/

RUN dotnet restore Coindesk.sln

COPY src/CoindeskApi src/CoindeskApi
WORKDIR /app/src/CoindeskApi
RUN dotnet publish -c Release -o /app/src/out


# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/src/out .
ENTRYPOINT [ "dotnet", "CoindeskApi.dll" ]